-- id: INT PRIMARY KEY
-- first_name: VARCHAR(30) to hold employee first name
-- last_name: VARCHAR(30) to hold employee last name
-- role_id: INT to hold employee role
-- manager_id: INT to hold reference to another employee that is the manager of the current employee (null if the employee has no manager)